/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.cCategoria;
import controlador.cCliente;
import controlador.cMarca;
import controlador.cProducto;
import controlador.cUnidadMedida;
import controlador.cVenta;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fekilo
 */
public class VistaVenta extends javax.swing.JDialog {

    //DefaultTableModel dtm;
    public VistaVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(this.getToolkit().getScreenSize());
        this.setLocationRelativeTo(null);
        eventosEscuchaComboBox();
        cVenta.controlTablaVenta();
        actualizarComboBox();
        jtxtFecha.setText(cVenta.mostrarFecha());
        jlbSerieNumero.setText(cVenta.mostrarNumeroSerieDoc());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jbtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbVenta = new javax.swing.JTable();
        jlbTotal = new javax.swing.JLabel();
        jlbSimboloSoles = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbProductos = new javax.swing.JTable();
        jtxtFiltroDescripcion = new javax.swing.JTextField();
        jbtnSeleccionarProducto = new javax.swing.JButton();
        jbtnBuscar = new javax.swing.JButton();
        jcboxUnidadMedida = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jcboxMarca = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcboxCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtCodigoCliente = new javax.swing.JTextField();
        jtxtNombreCliente = new javax.swing.JTextField();
        jbtnBuscarCliente = new javax.swing.JButton();
        jtxtApellidosCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcboxSexoCliente = new javax.swing.JComboBox<>();
        jbtnRegistrarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jbtnActualizar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jbtnVender = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jtxtFecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtxtCodigoBarras = new javax.swing.JTextField();
        jbtnFecha = new javax.swing.JButton();
        jlbSerieNumero = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel11.setBackground(new java.awt.Color(36, 36, 36));

        jbtnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        jbtnEliminar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminar.setText("X");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jtbVenta.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jtbVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Codigo", "Descripcion", "Und", "Cantidad", "precio", "total"
            }
        ));
        jtbVenta.setRowHeight(35);
        jtbVenta.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jtbVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbVentaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbVenta);
        if (jtbVenta.getColumnModel().getColumnCount() > 0) {
            jtbVenta.getColumnModel().getColumn(6).setMaxWidth(50);
        }

        jlbTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlbTotal.setText("00.00");

        jlbSimboloSoles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbSimboloSoles.setForeground(new java.awt.Color(255, 255, 255));
        jlbSimboloSoles.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbSimboloSoles.setText("S/");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jbtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbSimboloSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbSimboloSoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jtbProductos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jtbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodigoBarras", "Descripción", "PrecioVenta", "Categoria", "marca", "UnidadMedida", "En Almacen", "En Mostrador"
            }
        ));
        jtbProductos.setGridColor(new java.awt.Color(51, 51, 51));
        jtbProductos.setRowHeight(30);
        jtbProductos.setSelectionBackground(new java.awt.Color(47, 167, 77));
        jScrollPane2.setViewportView(jtbProductos);

        jtxtFiltroDescripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFiltroDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiltroDescripcionActionPerformed(evt);
            }
        });

        jbtnSeleccionarProducto.setBackground(new java.awt.Color(0, 204, 51));
        jbtnSeleccionarProducto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSeleccionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/flechaArriba.png"))); // NOI18N
        jbtnSeleccionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarProductoActionPerformed(evt);
            }
        });

        jbtnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jbtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/lupaProducto.png"))); // NOI18N
        jbtnBuscar.setText("BUSCAR");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jcboxUnidadMedida.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcboxUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboxUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxUnidadMedidaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 46, 6));
        jLabel8.setText("Ud Medida");

        jcboxMarca.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcboxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxMarcaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(6, 36, 16));
        jLabel7.setText("Marca");

        jcboxCategoria.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcboxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcboxCategoriaMouseExited(evt);
            }
        });
        jcboxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxCategoriaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 8, 8));
        jLabel6.setText("Categoría");

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRODUCTOS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtFiltroDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnBuscar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSeleccionarProducto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcboxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFiltroDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnSeleccionarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcboxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setText("CODIGO");

        jLabel2.setText("NOMBRES");

        jLabel3.setText("SEXO");

        jtxtCodigoCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtxtNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbtnBuscarCliente.setBackground(new java.awt.Color(204, 204, 204));
        jbtnBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/lupaCliente.png"))); // NOI18N
        jbtnBuscarCliente.setText("BUSCAR");
        jbtnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarClienteActionPerformed(evt);
            }
        });

        jtxtApellidosCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setText("APELLIDOS");

        jcboxSexoCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxSexoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Hombre", "Mujer" }));

        jbtnRegistrarCliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnRegistrarCliente.setText("REGISTRAR");
        jbtnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarClienteActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CLIENTE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jbtnActualizar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnActualizar.setText("ACTUALIZAR");
        jbtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCodigoCliente)
                            .addComponent(jtxtNombreCliente)
                            .addComponent(jtxtApellidosCliente)
                            .addComponent(jcboxSexoCliente, 0, 206, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnRegistrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcboxSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(245, 245, 245));

        jbtnVender.setBackground(new java.awt.Color(204, 102, 0));
        jbtnVender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnVender.setForeground(new java.awt.Color(255, 255, 255));
        jbtnVender.setText("VENDER");
        jbtnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(29, 28, 28));

        jtxtFecha.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jtxtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha");

        jPanel7.setBackground(new java.awt.Color(46, 45, 45));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Codigo Barras");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtxtCodigoBarras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoBarrasActionPerformed(evt);
            }
        });

        jbtnFecha.setBackground(new java.awt.Color(255, 255, 255));
        jbtnFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnFecha.setForeground(new java.awt.Color(255, 255, 255));
        jbtnFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/calendario.png"))); // NOI18N
        jbtnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFechaActionPerformed(evt);
            }
        });

        jlbSerieNumero.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlbSerieNumero.setForeground(new java.awt.Color(255, 255, 255));
        jlbSerieNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSerieNumero.setText("1 - 00001");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbSerieNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtnFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSerieNumero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jbtnFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFiltroDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiltroDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiltroDescripcionActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        if (jtxtFiltroDescripcion.getText().length() > 3) {
            actualizarTablaBuscar();
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jcboxUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboxUnidadMedidaActionPerformed

    private void jcboxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxMarcaActionPerformed

    }//GEN-LAST:event_jcboxMarcaActionPerformed

    private void jcboxCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcboxCategoriaMouseExited

    }//GEN-LAST:event_jcboxCategoriaMouseExited

    private void jcboxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxCategoriaActionPerformed

    }//GEN-LAST:event_jcboxCategoriaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jbtnSeleccionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarProductoActionPerformed
        Object[] obj = new Object[6];
        int fila = jtbProductos.getSelectedRow();
        if (fila > -1) {
            obj[0] = jtbProductos.getValueAt(fila, 0).toString();//id
            obj[1] = jtbProductos.getValueAt(fila, 1).toString();//codigo barras
            obj[2] = jtbProductos.getValueAt(fila, 2).toString();//descripcion
            obj[3] = jtbProductos.getValueAt(fila, 6).toString();//unidadMedida
            obj[4] = 1;//cantidad
            obj[5] = jtbProductos.getValueAt(fila, 3).toString();//precio
            //total
            //dtm.addRow(obj);
            jtbVenta.setModel(cVenta.agregarProducto(obj));
            camposCalculados(jtbVenta.getRowCount() - 1, 6);
            jtbVenta.getSelectionModel().setSelectionInterval(jtbVenta.getRowCount() - 1, jtbVenta.getRowCount() - 1);//pintar o seleccionar fila al agregar productos
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto !!");
        }
    }//GEN-LAST:event_jbtnSeleccionarProductoActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        int fila = jtbVenta.getSelectedRow();
        if (fila > -1) {
            jtbVenta.setModel(cVenta.quitarProducto(fila));
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto !!");
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVenderActionPerformed
        try {
            double especificarCantidad = Double.parseDouble(jtbVenta.getValueAt(jtbVenta.getSelectedRow(), 4).toString());
            int band = -1;
            if (jtbVenta.getRowCount() > 0 && especificarCantidad > 0) {
                String[] datosCliente = cCliente.leerId(jtxtCodigoCliente.getText());//Comprobar cliente
                if (!datosCliente[0].equalsIgnoreCase("")) {
                    band = cVenta.registrarVenta((DefaultTableModel) jtbVenta.getModel(), jtxtCodigoCliente.getText(), jtxtFecha.getText());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecciona productos para vender y especifique cantidad!!");
            }
            if (band != -1) {
                JOptionPane.showMessageDialog(null, "Registro de Venta lista!!");
                jtbVenta.setModel(new DefaultTableModel());
                cVenta.controlTablaVenta();
                jlbSerieNumero.setText(cVenta.mostrarNumeroSerieDoc());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Especifique cantidad del producto a vender!!");
        }
    }//GEN-LAST:event_jbtnVenderActionPerformed

    private void jbtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarClienteActionPerformed
        String[] datosCliente = cCliente.leerId(jtxtCodigoCliente.getText());
        try {
            if (!datosCliente[0].equalsIgnoreCase("") || datosCliente != null) {
                jtxtNombreCliente.setText(datosCliente[1]);
                jtxtApellidosCliente.setText(datosCliente[2]);
                jcboxSexoCliente.setSelectedIndex(Integer.parseInt(datosCliente[3]));
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jbtnBuscarClienteActionPerformed

    private void jbtnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarClienteActionPerformed
        int band = cCliente.registrar(jtxtCodigoCliente.getText(), jtxtNombreCliente.getText(), jtxtApellidosCliente.getText(), jcboxSexoCliente.getSelectedIndex());
        switch (band) {
            case 1:
                JOptionPane.showMessageDialog(this, "Registro de cliente lista !!");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Especifique todos los datos!!");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "El CODIGO debe estar conformado por Números!!");
                break;
        }
    }//GEN-LAST:event_jbtnRegistrarClienteActionPerformed

    private void jtxtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoBarrasActionPerformed

    private void jtbVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbVentaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int fila = jtbVenta.getSelectedRow();
            if (fila > -1) {
                camposCalculados(fila, 6);
                jtbVenta.getSelectionModel().setSelectionInterval(fila - 1, fila - 1);//pintar o seleccionar fila
            }
        }
    }//GEN-LAST:event_jtbVentaKeyPressed

    private void jbtnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFechaActionPerformed
        jtxtFecha.setText(cVenta.mostrarFecha());
    }//GEN-LAST:event_jbtnFechaActionPerformed

    private void jbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarActionPerformed
        int band = cCliente.actualizar(jtxtCodigoCliente.getText(), jtxtNombreCliente.getText(), jtxtApellidosCliente.getText(), jcboxSexoCliente.getSelectedIndex());
        switch (band) {
            case 1:
                JOptionPane.showMessageDialog(this, "Actualización de cliente lista !!");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Especifique todos los datos!!");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "El CODIGO no acepta letras!!");
                break;
        }
    }//GEN-LAST:event_jbtnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaVenta dialog = new VistaVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnBuscarCliente;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnFecha;
    private javax.swing.JButton jbtnRegistrarCliente;
    private javax.swing.JButton jbtnSeleccionarProducto;
    private javax.swing.JButton jbtnVender;
    private javax.swing.JComboBox<String> jcboxCategoria;
    private javax.swing.JComboBox<String> jcboxMarca;
    private javax.swing.JComboBox<String> jcboxSexoCliente;
    private javax.swing.JComboBox<String> jcboxUnidadMedida;
    private javax.swing.JLabel jlbSerieNumero;
    private javax.swing.JLabel jlbSimboloSoles;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JTable jtbProductos;
    public javax.swing.JTable jtbVenta;
    private javax.swing.JTextField jtxtApellidosCliente;
    private javax.swing.JTextField jtxtCodigoBarras;
    private javax.swing.JTextField jtxtCodigoCliente;
    private javax.swing.JTextField jtxtFecha;
    private javax.swing.JTextField jtxtFiltroDescripcion;
    private javax.swing.JTextField jtxtNombreCliente;
    // End of variables declaration//GEN-END:variables

    public void acomodarTablaVenta() {
        jtbVenta.getTableHeader().setFont(new Font("Verdana", 1, 18));
        jtbVenta.getColumnModel().getColumn(0).setMaxWidth(0);
        jtbVenta.getColumnModel().getColumn(0).setMinWidth(0);
        jtbVenta.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jtbVenta.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jtbVenta.getColumnModel().getColumn(2).setMinWidth(400);
    }

    public void actualizarTablaBuscar() {
        this.jtbProductos.setModel(cProducto.leerDescripcion(jtxtFiltroDescripcion.getText()));
        jtbProductos.getTableHeader().setFont(new Font("Verdana", 1, 18));
        jtbProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getColumnModel().getColumn(0).setMinWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jtbProductos.getColumnModel().getColumn(2).setMinWidth(400);
    }

    public void actualizarTablaFiltro() {
        this.jtbProductos.setModel(cProducto.leerFiltro(jcboxCategoria.getSelectedItem().toString(), jcboxMarca.getSelectedItem().toString(), jcboxUnidadMedida.getSelectedItem().toString()));
        jtbProductos.getTableHeader().setFont(new Font("Verdana", 1, 18));
        jtbProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getColumnModel().getColumn(0).setMinWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jtbProductos.getColumnModel().getColumn(2).setMinWidth(400);
    }

    public void actualizarComboBox() {
        jcboxCategoria.setModel(cCategoria.leerCombo());
        jcboxMarca.setModel(cMarca.leerCombo());
        jcboxUnidadMedida.setModel(cUnidadMedida.leerCombo());
    }

    public void eventosEscuchaComboBox() {
        jcboxCategoria.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                actualizarTablaFiltro();
            }
        });
        jcboxMarca.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                actualizarTablaFiltro();
            }
        });
        jcboxUnidadMedida.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                actualizarTablaFiltro();
            }
        });
    }

    ;
    
    public void camposCalculados(int fila, int columna) {
        jtbVenta.setValueAt(cVenta.calcularTotal((DefaultTableModel) jtbVenta.getModel(), fila), fila, columna);
        jlbTotal.setText(Double.toString(cVenta.calculaSumaTotal((DefaultTableModel) jtbVenta.getModel(), columna)));
        acomodarTablaVenta();
    }
}
