/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.cCategoria;
import controlador.cMarca;
import controlador.cProducto;
import controlador.cUnidadMedida;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Fekilo
 */
public class VistaInventario extends javax.swing.JDialog {

    /**
     * Creates new form VistaInventario
     */
    public VistaInventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(this.getToolkit().getScreenSize());
        this.setLocationRelativeTo(null);
        eventosEscuchaComboBox();
        actualizarTablaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbProductos = new javax.swing.JTable();
        jbtnRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jcboxCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtbnRegistrarCategoria = new javax.swing.JButton();
        jbtnRegistrarMarca = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcboxMarca = new javax.swing.JComboBox<>();
        jcboxUnidadMedida = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jbtnRegistrarUndMedida = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();
        jtxtFiltroDescripcion = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jbtnListarTodos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(251, 247, 247));

        jtbProductos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jtbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbProductos.setGridColor(new java.awt.Color(51, 51, 51));
        jtbProductos.setRowHeight(30);
        jtbProductos.setSelectionBackground(new java.awt.Color(47, 167, 77));
        jScrollPane1.setViewportView(jtbProductos);

        jbtnRegistrar.setBackground(new java.awt.Color(35, 124, 57));
        jbtnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrar.setText("REGISTRAR PRODUCTO");
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });

        jcboxCategoria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcboxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcboxCategoriaMouseExited(evt);
            }
        });
        jcboxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxCategoriaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 8, 8));
        jLabel6.setText("Categoría");

        jtbnRegistrarCategoria.setBackground(new java.awt.Color(192, 47, 47));
        jtbnRegistrarCategoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtbnRegistrarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jtbnRegistrarCategoria.setText("+");
        jtbnRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnRegistrarCategoriaActionPerformed(evt);
            }
        });

        jbtnRegistrarMarca.setBackground(new java.awt.Color(35, 124, 57));
        jbtnRegistrarMarca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnRegistrarMarca.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarMarca.setText("+");
        jbtnRegistrarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarMarcaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(6, 36, 16));
        jLabel7.setText("Marca");

        jcboxMarca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcboxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxMarcaActionPerformed(evt);
            }
        });

        jcboxUnidadMedida.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcboxUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcboxUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxUnidadMedidaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 46, 6));
        jLabel8.setText("Ud Medida");

        jbtnRegistrarUndMedida.setBackground(new java.awt.Color(149, 149, 38));
        jbtnRegistrarUndMedida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnRegistrarUndMedida.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarUndMedida.setText("+");
        jbtnRegistrarUndMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarUndMedidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbnRegistrarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnRegistrarMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnRegistrarUndMedida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnRegistrarCategoria)
                    .addComponent(jLabel7)
                    .addComponent(jcboxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRegistrarMarca)
                    .addComponent(jLabel8)
                    .addComponent(jcboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRegistrarUndMedida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        jbtnEliminar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminar.setText("X");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jbtnActualizar.setBackground(new java.awt.Color(153, 153, 0));
        jbtnActualizar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnActualizar.setText("ACTUALIZAR");
        jbtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarActionPerformed(evt);
            }
        });

        jtxtFiltroDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiltroDescripcionActionPerformed(evt);
            }
        });

        jbtnBuscar.setBackground(new java.awt.Color(77, 98, 159));
        jbtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBuscar.setText("BUSCAR");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jbtnListarTodos.setBackground(new java.awt.Color(86, 148, 136));
        jbtnListarTodos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnListarTodos.setForeground(new java.awt.Color(255, 255, 255));
        jbtnListarTodos.setText("LISTAR TODOS");
        jbtnListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtFiltroDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnListarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnActualizar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRegistrar)
                    .addComponent(jtxtFiltroDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscar)
                    .addComponent(jbtnListarTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76))
        );

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("INVENTARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
        VistaRegistroProducto vRegistroProducto = new VistaRegistroProducto(null, rootPaneCheckingEnabled);
        vRegistroProducto.setVisible(true);
        
    }//GEN-LAST:event_jbtnRegistrarActionPerformed

    private void jtbnRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnRegistrarCategoriaActionPerformed
        VistaCategoria vCategoria = new VistaCategoria(null, rootPaneCheckingEnabled);
        vCategoria.setVisible(true);
    }//GEN-LAST:event_jtbnRegistrarCategoriaActionPerformed

    private void jbtnRegistrarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarMarcaActionPerformed
        VistaMarca vMarca = new VistaMarca(null, rootPaneCheckingEnabled);
        vMarca.setVisible(true);
    }//GEN-LAST:event_jbtnRegistrarMarcaActionPerformed

    private void jbtnRegistrarUndMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarUndMedidaActionPerformed
        VistaUnidadMedida vUnidadMedida = new VistaUnidadMedida(null, rootPaneCheckingEnabled);
        vUnidadMedida.setVisible(true);
    }//GEN-LAST:event_jbtnRegistrarUndMedidaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        actualizarComboBox();
        actualizarTablaProductos();
    }//GEN-LAST:event_formWindowActivated

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        int fila = jtbProductos.getSelectedRow();
        if (fila > -1) {
            String id = jtbProductos.getValueAt(fila, 0).toString();
            cProducto.eliminar(id);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un PRODUCTO !!");
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarActionPerformed
        int fila = jtbProductos.getSelectedRow();
        if (fila > -1) {
            String idArticulo = jtbProductos.getValueAt(fila, 0).toString();
            String codigoBarras = jtbProductos.getValueAt(fila, 1).toString();
            String descripcion = jtbProductos.getValueAt(fila, 2).toString();
            String precioVenta = jtbProductos.getValueAt(fila, 3).toString();
            String categoria = jtbProductos.getValueAt(fila, 4).toString();
            String marca = jtbProductos.getValueAt(fila, 5).toString();
            String unidadMedida = jtbProductos.getValueAt(fila, 6).toString();
            //MODIFICAR Y HACERLO CON CONBOBOX, actualizar marca, categoria y unidad de medida no funciona---------------------------------------------------------------------------
            cProducto.actualizar(idArticulo, descripcion, precioVenta, codigoBarras, categoria, marca, unidadMedida);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un PRODUCTO !!");
        }
    }//GEN-LAST:event_jbtnActualizarActionPerformed

    private void jcboxCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcboxCategoriaMouseExited

    }//GEN-LAST:event_jcboxCategoriaMouseExited

    private void jcboxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxCategoriaActionPerformed

    }//GEN-LAST:event_jcboxCategoriaActionPerformed

    private void jcboxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxMarcaActionPerformed

    }//GEN-LAST:event_jcboxMarcaActionPerformed

    private void jcboxUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboxUnidadMedidaActionPerformed

    private void jbtnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListarTodosActionPerformed
        actualizarTablaProductos();
    }//GEN-LAST:event_jbtnListarTodosActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        if (jtxtFiltroDescripcion.getText().length() > 3) {
            actualizarTablaBuscar();
        }
        
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jtxtFiltroDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiltroDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiltroDescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaInventario dialog = new VistaInventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnListarTodos;
    private javax.swing.JButton jbtnRegistrar;
    private javax.swing.JButton jbtnRegistrarMarca;
    private javax.swing.JButton jbtnRegistrarUndMedida;
    private javax.swing.JComboBox<String> jcboxCategoria;
    private javax.swing.JComboBox<String> jcboxMarca;
    private javax.swing.JComboBox<String> jcboxUnidadMedida;
    private javax.swing.JTable jtbProductos;
    private javax.swing.JButton jtbnRegistrarCategoria;
    private javax.swing.JTextField jtxtFiltroDescripcion;
    // End of variables declaration//GEN-END:variables

    public void actualizarTablaProductos() {
        this.jtbProductos.setModel(cProducto.leer());
        jtbProductos.getTableHeader().setFont(new Font("Verdana", 1, 18));
        jtbProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getColumnModel().getColumn(0).setMinWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }
    
    public void actualizarTablaFiltro() {
        this.jtbProductos.setModel(cProducto.leerFiltro(jcboxCategoria.getSelectedItem().toString(), jcboxMarca.getSelectedItem().toString(), jcboxUnidadMedida.getSelectedItem().toString()));
        jtbProductos.getTableHeader().setFont(new Font("Verdana", 1, 18));
        jtbProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getColumnModel().getColumn(0).setMinWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }
    
    public void actualizarTablaBuscar() {
        this.jtbProductos.setModel(cProducto.leerDescripcion(jtxtFiltroDescripcion.getText()));
        jtbProductos.getTableHeader().setFont(new Font("Verdana", 1, 18));
        jtbProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getColumnModel().getColumn(0).setMinWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jtbProductos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    public void actualizarComboBox() {
        jcboxCategoria.setModel(cCategoria.leerCombo());
        jcboxMarca.setModel(cMarca.leerCombo());
        jcboxUnidadMedida.setModel(cUnidadMedida.leerCombo());
    }
    
    public void eventosEscuchaComboBox(){
    jcboxCategoria.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                actualizarTablaFiltro();
            }
        });
        jcboxMarca.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                actualizarTablaFiltro();
            }
        });
        jcboxUnidadMedida.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                actualizarTablaFiltro();
            }
        });
    };
    
    
   
    
}
